name: biocide-resistance-scanner
channels:
  - anaconda
  - conda-forge
  - bioconda
dependencies:
  - python=3.7
  - perl-bioperl>=1.7.2
  - perl-bioperl-core
  - islandpath
  - abricate
  - blast
  - pip
  - pip:
    - -r requirements.txt
