name: biocide-resistance-scanner
channels:
  - anaconda
  - conda-forge
  - bioconda
  - cyclus
dependencies:
  - python=3.7
  - abricate
  - platon
  - pip
  - java-jre
  - jupyter
  - phispy
  - pip:
    - -r requirements.txt
